# Number of days of inactivity before an issue becomes stale
daysUntilStale: 7
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - important
# Label to use when marking an issue as stale
staleLabel: 🥀 stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  这一 issue 很久没有动静了，我会将其按照「已过期」进行处理。如果之后仍然没有动静，
  我会直接关闭这一 issue，感谢您对项目做出的贡献。💗
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
